-- Ensure trade-customer master columns exist (CoA + Information + policies).
-- Safe to re-run. Prefer: pnpm --filter database-pg push

ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS old_code text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS party_type text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS speciality text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS store_type text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS contact_person text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS nic_number text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS ntn_number text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS passport_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS land_line text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS customer_class text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS detailed_address text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS city_name text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS reg_date date;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS credit_category text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS monthly_sales_target_pkr integer NOT NULL DEFAULT 0;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS mode_of_payment text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS timing text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS visit_frequency integer NOT NULL DEFAULT 0;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS visiting_days_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS terms_of_payment text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_9_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_9_expiry date;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_10_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_10_expiry date;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_11_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS license_11_expiry date;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS adv_tax_type text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS is_foc_customer boolean NOT NULL DEFAULT false;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS can_deduct_tax boolean NOT NULL DEFAULT false;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS tax_pct integer NOT NULL DEFAULT 0;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS discount_policy_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS bonus_policy_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS company_credit_limits_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS company_ids_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS block_sales_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS others_json text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS location_lat text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS location_lng text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS location_notes text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS account_type text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS company_code text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS unique_name text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS postal_address text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS province text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS fax text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS party_mode text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS stx_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS sector text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS licence_no text;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS licence_expiry date;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS active_tax_payer boolean NOT NULL DEFAULT false;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS income_tax_exempt boolean NOT NULL DEFAULT false;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS advance_tax_summary boolean NOT NULL DEFAULT false;
ALTER TABLE pharmacy_trade_customers ADD COLUMN IF NOT EXISTS invoice_warranty boolean NOT NULL DEFAULT false;
